### ISSUE TITLE
report.json is empty

### ISSUE THREAD

**Issue by foolip** [w3c/cg-monitor#9]
https://github.com/w3c/cg-monitor/blob/8de6ab3c09cfa24aa0c54b8c5d465330244fa638/report.json is empty, or rather `data` is an empty array.

This probably bad, because https://github.com/w3c/validate-repos consumes this file.

@dontcallmedom do you know what's going on with this?

**Comment by dontcallmedom** [comment]
this happened [3 days ago](https://github.com/w3c/cg-monitor/commit/8de6ab3c09cfa24aa0c54b8c5d465330244fa638#diff-76a84217c1c1e1d7ecf1a6de26061bb3) apparently... Will look into it

**Comment by dontcallmedom** [comment]
hmm... ran it manually, and didn't get the problem; probably a motivation to migrate this tool to github action too at some point

**Comment by foolip** [comment]
Do you think it'll recover by itself, does this happen when there's a network error or something?

**Comment by dontcallmedom** [comment]
(updates have been prevented from publishing empty reports for a long while now, closing)
